### ISSUE TITLE
i don't know how to contact you, so i can only use this method. i am a student in bupt, China. I am writing my graduation papers about TDT and i really requires this data. Please give me your contact infomation, i want to explain. Please，拜托了🙏

### ISSUE THREAD

**Issue by xiaoquantou** [heyan4869/TDT4-Clustering#2]

**Comment by heyan4869** [comment]
I'm not sure if I made myself clear in the previous comment, but I personally have **no right** to share any dataset from that course with anyone. Even though you do need the dataset, I still can't give it to you, not because I don't want to but because I simply **can't**. 
However, it looks like UPENN has that data as well [https://catalog.ldc.upenn.edu/LDC2005T16](url) and you can try to reach out to them and see if they can share with you. Just explain to them your case and the fact that you are still a student and might not be able to afford purchasing it.
In the end, if you can not even get the dataset for your graduation project, you might need to think about whether to pursue this topic or not. 
Best luck to you!
